[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "Gr9GxKWgvEY4dpRBPz4g1QZ3qUmYVJg7wLCzTQbxXW4R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ishan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
